# Generated by Django 4.2.3 on 2023-08-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('tags', models.CharField(max_length=200)),
                ('thumbnail_image', models.ImageField(upload_to='blogs/thumbnails/')),
                ('likes', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'blogs',
            },
        ),
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('catch_copy', models.CharField(max_length=200)),
                ('thumbnail_image', models.ImageField(upload_to='board_game_blogs/thumbnails/')),
                ('category', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('min_players', models.PositiveIntegerField()),
                ('max_players', models.PositiveIntegerField()),
                ('tag_flag', models.BooleanField(default=False)),
                ('min_play_time', models.PositiveIntegerField()),
                ('max_play_time', models.PositiveIntegerField()),
                ('min_age', models.PositiveIntegerField()),
                ('max_age', models.PositiveIntegerField()),
                ('likes', models.PositiveIntegerField(default=0)),
                ('reads', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'product_descriptions',
            },
        ),
    ]
