# Generated by Django 4.2.3 on 2023-08-01 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdescription',
            options={'verbose_name': '商品説明', 'verbose_name_plural': '商品説明'},
        ),
    ]
