# Generated by Django 4.2.3 on 2023-08-01 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_productdescription_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'ブログ', 'verbose_name_plural': 'ブログ'},
        ),
    ]
