# Generated by Django 4.2.3 on 2023-08-02 02:47

import backend.models.PhotoModel
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_photo_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=backend.models.PhotoModel.get_image_upload_path),
        ),
    ]
