# Generated by Django 4.2.3 on 2023-08-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_blog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdescription',
            name='max_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productdescription',
            name='max_play_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
