# Generated by Django 4.2.3 on 2023-08-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdescription',
            name='max_players',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productdescription',
            name='min_play_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productdescription',
            name='min_players',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
