# Generated by Django 4.2.3 on 2023-08-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_productdescription_max_players_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdescription',
            name='min_age',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
