# Generated by Django 4.2.3 on 2023-08-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_productdescription_min_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdescription',
            name='photos',
            field=models.ManyToManyField(to='backend.photo'),
        ),
    ]
