# Generated by Django 4.2.3 on 2023-08-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_productdescription_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdescription',
            name='content',
            field=models.TextField(),
        ),
    ]
