# Generated by Django 4.2.3 on 2023-08-05 17:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_productdescription_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdescription',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
